# Generated by Django 5.2.5 on 2025-09-01 23:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(max_length=15)),
                ('cat_desc', models.TextField(blank=True, null=True)),
                ('cat_foto', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=40)),
                ('cli_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('cli_titulo_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('cli_direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('cli_ciudad', models.CharField(blank=True, max_length=15, null=True)),
                ('cli_region', models.CharField(blank=True, max_length=15, null=True)),
                ('cli_codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('cli_pais', models.CharField(blank=True, max_length=15, null=True)),
                ('cli_telefono', models.CharField(blank=True, max_length=24, null=True)),
                ('cli_mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nombre', models.CharField(max_length=20)),
                ('emp_apellido', models.CharField(max_length=10)),
                ('emp_titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_fechanac', models.DateField(blank=True, null=True)),
                ('emp_fecha_contrato', models.DateField(blank=True, null=True)),
                ('emp_direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('emp_celular', models.CharField(blank=True, max_length=24, null=True)),
                ('emp_foto', models.BinaryField(blank=True, null=True)),
                ('emp_notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('prv_empresa', models.CharField(max_length=40)),
                ('prv_giro', models.CharField(blank=True, max_length=20, null=True)),
                ('prv_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('prv_direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('prv_cod_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('prv_telefono', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('ord_fecha', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='Pfront.cliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='Pfront.empleado')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=40)),
                ('pro_descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('pro_precio', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('pro_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Pfront.categoria')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Pfront.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Pfront.orden')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='Pfront.producto')),
            ],
            options={
                'verbose_name': 'Detalle de orden',
                'verbose_name_plural': 'Detalles de orden',
                'db_table': 'detalle_orden',
            },
        ),
    ]
